version: 2
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
-
  id: gh-star-history-linux
  env:
    - CGO_ENABLED=0
  goos:
    - linux
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-star-history.version={{.Version}} -X github.com/k1LoW/gh-star-history.commit={{.FullCommit}} -X github.com/k1LoW/gh-star-history.date={{.Date}} -X github.com/k1LoW/gh-star-history/version.Version={{.Version}}
-
  id: gh-star-history-darwin
  env:
    - CGO_ENABLED=0
  goos:
    - darwin
  goarch:
    - amd64
    - arm64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-star-history.version={{.Version}} -X github.com/k1LoW/gh-star-history.commit={{.FullCommit}} -X github.com/k1LoW/gh-star-history.date={{.Date}} -X github.com/k1LoW/gh-star-history/version.Version={{.Version}}
-
  id: gh-star-history-windows
  env:
    - CGO_ENABLED=0
  goos:
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/k1LoW/gh-star-history.version={{.Version}} -X github.com/k1LoW/gh-star-history.commit={{.FullCommit}} -X github.com/k1LoW/gh-star-history.date={{.Date}} -X github.com/k1LoW/gh-star-history/version.Version={{.Version}}
archives:
-
  id: gh-star-history-archive
  name_template: '{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format_overrides:
    - goos: darwin
      format: zip
  files:
    - CREDITS
    - README.md
    - CHANGELOG.md
-
  id: gh-star-history-binary
  name_template: '{{ .Binary }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
  format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
nfpms:
  - id: gh-star-history-nfpms
    file_name_template: "{{ .ProjectName }}_{{ .Version }}-1_{{ .Arch }}"
    builds:
      - gh-star-history-linux
    homepage: https://github.com/k1LoW/gh-star-history
    maintainer: Ken'ichiro Oyama <k1lowxb@gmail.com>
    description: Show star history of repositories.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin
    epoch: 1
release:
  draft: true
  replace_existing_draft: true
